### ISSUE TITLE
There is no test command

### ISSUE THREAD

**Issue by andho** [maport/docker-elm#10]
I'm trying the following command:

    docker run --rm -it codesimple/elm:0.19 test

And get the following output:

    There is no test command. Try repl, init, or bump instead?
    
    Run `elm` with no arguments to get more hints.

**Comment by maport** [comment]
`elm-test` was removed in version 0.19 but I see there was still a reference to it in the readme. I have now removed that.

I can't recall why it was removed. I think perhaps at the time it wasn't available for version 0.19 but it seems it may be now. I'm not currently using `elm` so haven't had a chance to try it out.

**Comment by andho** [comment]
Oh okay. Didn't know that. I created a separate container for testing with elm-test installed. Closing as a non issue.
